// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace wordNote.Migrations
{
    [DbContext(typeof(RazorPagesWordContext))]
    partial class RazorPagesWordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("wordNote.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Line")
                        .HasColumnType("TEXT");

                    b.Property<string>("Person")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .HasColumnType("TEXT");

                    b.Property<string>("Span")
                        .HasColumnType("TEXT");

                    b.Property<string>("Submitter")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Word");
                });
#pragma warning restore 612, 618
        }
    }
}
